version: '3.9'
services:
  fm-server:
    privileged: true
    image: rikpet/easy-living:fm-server-beta
    container_name: fm-server
    ports:
      - 5010:5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_ENV=development
      - DOCKER_HUB_USERNAME
      - DOCKER_HUB_PASSWORD
      - DOCKER_HUB_REPO