name: Build and Test

on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev_requirements.txt 
    - name: Analysing the code with pylint
      run: |
        pylint --fail-under=9.5 $(git ls-files '*.py')
    - name: Running tests
      env: 
        PATH_WORK_DIR: ${{ github.workspace }}
      run: |
        pytest
