# Publish log server image to docker hub from master
name: Release

on:   
  push:
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  workflow_dispatch:  # Makes it possible to trigger manually

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: rikpet
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push application; Fleet manager client 
        id: docker_build_fm_client
        uses: docker/build-push-action@v2
        with:
          context: client
          tags: rikpet/easy-living:fm-client-${{ secrets.DOCKER_TAG }}
          push: true
          pull: true

      - name: Build and push application; Fleet manager server 
        id: docker_build_fm_server
        uses: docker/build-push-action@v2
        with:
          context: server
          tags: rikpet/easy-living:fm-server-${{ secrets.DOCKER_TAG }}
          push: true
          pull: true
